paths:
  /api/products/product:
    get:
      summary: Obtiene todos los productos de la tienda
      tags:
        - Product
      responses:
        "200":
          description: Devuelve una lista de los productos
          content:
            application/json:
                schema:
                  type: object
                  properties:
                      _id: 
                        type: String
                        description: id gestionanda por mongo
                      name:
                        type: String
                        description: nombre del producto
                      description:
                        type: String
                        description: descripcion del producto
                      image:
                        type: String
                        description: link subido por multer
                      code:
                        type: String
                        description: codigo del producto
                      price:
                        type: Number
                        description: precio del producto
                      stock:
                        type: Number
                        description: stock del producto
  /api/products/{id}:
    parameters:
            -   name: id
                in: path
                description: Representa al _id del producto guardado en Mongo
                schema:
                    type: string
    get:
      summary: Obtenemos la informacion de un producto en especifico
      tags:
        - Product
      responses:
        "200":
          description: Devuelve la informacion del producto del codigo pasado
          content:
            application/json:
                schema:
                  type: object
                  properties:
                      _id: 
                        type: String
                        description: id gestionanda por mongo
                      name:
                        type: String
                        description: nombre del producto
                      description:
                        type: String
                        description: descripcion del producto
                      image:
                        type: String
                        description: link subido por multer
                      code:
                        type: String
                        description: codigo del producto
                      price:
                        type: Number
                        description: precio del producto
                      stock:
                        type: Number
                        description: stock del producto
      

